INSERT INTO BUILDING(ID, NAME) VALUES (1, 'TEST');
INSERT INTO BUILDING(ID, NAME) VALUES (2, 'TEST2');

INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-10, 'Room1', 1,1);
INSERT INTO ROOM(ID, NAME, FLOOR, BUILDING_ID) VALUES(-9, 'Room2', 1,2);

INSERT INTO LIGHT(ID, ROOM_ID, LEVEL, STATUS) VALUES (-1, -10, 8, 'ON');
INSERT INTO LIGHT(ID, ROOM_ID, LEVEL, STATUS) VALUES (-2,-10, 0, 'OFF');